### ISSUE TITLE
How to get started

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet-management-server#7]
Dear Team,

We are unable to setup edumeet, using management-server. can some one help on the configuration.

**Comment by N7Remus** [comment]
Hi, please have a look into:
https://github.com/edumeet/edumeet-docker/tree/4.x-kc2

I made a complete docker-compose install, nearly step by step.
Run  ./run-me-first.sh . For setup details.

The management server setup is not yet user firendly. 
I made some curl examples in the mgmt.sh .
You have to: 
[with edumeet-admin which is hardcoded at the moment in the mgmt server]
- create a tenant 
- create a tenant fqdn
- add tenanOauths
[with a user jwt from a now added tenant]
- register a room 

Im working on the edumeet-management-client so you can configure it with UI.

After you logged in you can use the created room.

**Comment by N7Remus** [comment]
Hi, docs should be up to date now.

**Comment by bianxg** [comment]
yarn test
yarn run v1.22.22
$ cross-env NODE_ENV=test npm run migrate && npm run mocha

> edumeet-management-server@0.1.0 migrate
> knex migrate:latest

Requiring external module ts-node/register
WARNING: NODE_ENV value of 'test' did not match any deployment config file names.
WARNING: See https://github.com/node-config/node-config/wiki/Strict-Mode
warn: Publishing all events to all authenticated users. See `channels.ts` and https://dove.feathersjs.com/api/channels.html for more information.
Already up to date

> edumeet-management-server@0.1.0 mocha
> cross-env NODE_ENV=test mocha test/ --require ts-node/register --recursive --extension .ts --exit

WARNING: NODE_ENV value of 'test' did not match any deployment config file names.
WARNING: See https://github.com/node-config/node-config/wiki/Strict-Mode
warn: Publishing all events to all authenticated users. See `channels.ts` and https://dove.feathersjs.com/api/channels.html for more information.


  Feathers application tests
    1) starts and shows the index page
    2) shows a 404 JSON error

  application client tests
    ✔ initialized the client
    3) creates and authenticates a user with email and password

  groupUsers service
    ✔ registered the service

  groups service
    ✔ registered the service

  permissions service
    ✔ registered the service

  rolePermissions service
    ✔ registered the service

  roles service
    ✔ registered the service

  roomGroupRoles service
    ✔ registered the service

  roomOwners service
    ✔ registered the service

  roomUserRoles service
    ✔ registered the service

  rooms service
    ✔ registered the service

  tenantAdmins service
    ✔ registered the service

  tenantFQDNs service
    ✔ registered the service

  tenantOwners service
    ✔ registered the service

  tenants service
    ✔ registered the service

  users service
    ✔ registered the service


  15 passing (2s)
  3 failing

  1) Feathers application tests
       starts and shows the index page:
     AxiosError: Request failed with status code 503
      at settle (node_modules/axios/lib/core/settle.js:19:12)
      at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:589:11)
      at IncomingMessage.emit (node:events:529:35)
      at IncomingMessage.emit (node:domain:489:12)
      at endReadableNT (node:internal/streams/readable:1400:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)

  2) Feathers application tests
       shows a 404 JSON error:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

503 !== 404

      + expected - actual

      -503
      +404

      at Context.<anonymous> (test/app.test.ts:38:11)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

  3) application client tests
       creates and authenticates a user with email and password:
     Error: [object Object]
      at convert (node_modules/@feathersjs/errors/src/index.ts:266:7)
      at toError (node_modules/@feathersjs/rest-client/src/base.ts:11:16)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Context.<anonymous> (test/client.test.ts:43:3)



error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by bianxg** [comment]
curl 'http://localhost:3030/users/' -H 'Content-Type: application/json' --data-binary '{ "email": "edumeet@edu.meet", "password": "edumeet" }'
{"name":"NotAuthenticated","message":"Not authenticated","code":401,"className":"not-authenticated"}
